steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args: 
  - '-c'
  - |
    echo 123
    echo 456
    echo 789

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/nginx-2:$COMMIT_SHA', '.' ]
  dir: "API/"

- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/nginx-2:$COMMIT_SHA"]

- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - '${_DEPLOYMENT_NAME}'
  - '${_POD_SPEC}=gcr.io/$PROJECT_ID/quotations-management:$COMMIT_SHA'
  - '--namespace'
  - 'default'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  
images: ['gcr.io/$PROJECT_ID/quotations-management:$COMMIT_SHA']  